### ISSUE TITLE
哈哈哈哈

### ISSUE THREAD

**Issue by AntiMoron** [lhy0403/Spring12#5]
嗝

**Comment by lhy0403** [comment]
？？？这是什么外星文明Issue？

**Comment by AntiMoron** [comment]
你怎么不merge.还等单独fork维护的吗

**Comment by lhy0403** [comment]
其实本来想merge的，但是原作者好像不怎么上线，我这边只能等到他那几个pull request全都merge了以后才能没有 conflict，，所以就先等等了

**Comment by AntiMoron** [comment]
垃圾原作者

**Comment by lhy0403** [comment]
哈哈哈哈不能这么说，，人家毕竟是原创
